= HDP_04 Execution Requisites

HDP_04 Execution Requisites

== Features

- Syncs HDFS /user directories with users found from LDAP
- Creates `s3credentials` secret file for each user

== Documentation

See the official documentation on https://docs.teragrep.com[docs.teragrep.com].

== Limitations

Must be built on Java 11.

== How to compile

[source,bash]
----
JAVA_HOME=/usr/lib/jvm/java-11-openjdk mvn clean package
----

== How to use

Directly:

[source,bash]
----
java -jar hdp_04.jar
----

Via systemd file:

[source,bash]
----
systemctl start hdp_04
----

== Contributing

// Change the repository name in the issues link to match with your project's name

You can involve yourself with our project by https://github.com/teragrep/repo-template/issues/new/choose[opening an issue] or submitting a pull request.

Contribution requirements:

. *All changes must be accompanied by a new or changed test.* If you think testing is not required in your pull request, include a sufficient explanation as why you think so.
. Security checks must pass
. Pull requests must align with the principles and http://www.extremeprogramming.org/values.html[values] of extreme programming.
. Pull requests must follow the principles of Object Thinking and Elegant Objects (EO).

Read more in our https://github.com/teragrep/teragrep/blob/main/contributing.adoc[Contributing Guideline].

=== Contributor License Agreement

Contributors must sign https://github.com/teragrep/teragrep/blob/main/cla.adoc[Teragrep Contributor License Agreement] before a pull request is accepted to organization's repositories.

You need to submit the CLA only once. After submitting the CLA you can contribute to all Teragrep's repositories.
